# inspired by exoplanet:
# https://github.com/exoplanet-dev/exoplanet/blob/master/.pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace

      - id: end-of-file-fixer

      - id: debug-statements

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: tests, *.tex
      - id: isort
        name: isort (cython)
        types: [cython]
        exclude: tests, *.tex
      - id: isort
        name: isort (pyi)
        types: [pyi]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
        exclude: cv/scripts/__init__.py, *.tex


  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
