coverage:
  precision: 2
  round: nearest
  range: "40...90"
  ignore:
    - "__init__.py"
    - "tests"
    - "scripts/utf8totex.py"
    - "scripts/__init__.py"
    - "cv/scripts/utf8totex.py"
    - "cv/scripts/__init__.py"
