name: Docs
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs twice a day
    - cron:  '*/5 * * * *'
jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.6

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          
      - name: Scrape the number of JOSS reviews
        env:
          SHEETS_SECRET: ${{ secrets.SHEETS_SECRET }}
        run: |
          python scrape_joss.py SHEETS_SECRET
          
      - name: Write the number of JOSS reviews
        run: |
          python write_joss.py
          
      - name: Committing changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Running tutorial notebooks on newest release
