name: Tests
env:
  ADS_DEV_KEY: ${{secrets.ADS_SECRET}}
  SHEETS_SECRET: ${{ secrets.SHEETS_API_KEY }}
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events only for main branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of >=1 jobs, run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of job
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: 3.8
      - name: Run tests
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --upgrade setuptools
          python3 -m pip install -e .
          pip3 install pytest
          pip3 install pytest-cov
          pip3 install codecov
          coverage run -m unittest discover .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
